site_name: GSB retreat
# site_url:
site_description: GSB retreat organization team

# repo_url: https://github.com/yehzx/{repo}
# repo_name: yehzx/{repo}

theme:
  name: material
  highlightjs: true
  features:
    - navigation.instant
    - navigation.top
  palette:
    primary: blue grey

markdown_extensions:
  - pymdownx.tilde
  - pymdownx.betterem
  - attr_list
  - md_in_html

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Asia/Taipei

nav:
  - Overview: 'index.md'
  - Public Relations: 'public_relations.md'
  - Equipment: 'equipment.md'
  - Event Planning: 'event_planning.md'
  - Artistic Design: 'artistic_design.md' 
  - Coordinator: 'coordinator.md'
  - Meeting Minutes: 'meeting_minutes.md'